name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Test with pytest
      run: |
        git config --global user.email "test@example.com"
        git config --global user.name "test"
        git config --global init.defaultBranch "master"
        ssh-keygen -f ~/.ssh/id_rsa -N ""
        pytest
